name: Sync with Jira - PR Closed

on:
  workflow_call:
    secrets:
      caller_jira_auth:
        required: true

jobs:
  extract:
    name: Extract Jira keys from PR
    uses: scylladb/github-automation/.github/workflows/extract_jira_keys.yml@main
    with:
      pr_title: ${{ github.event.pull_request.title }}
      pr_body:  ${{ github.event.pull_request.body }}
    secrets:
      jira_auth: ${{ secrets.caller_jira_auth }}

  debug:
    name: Debug data
    needs: extract
    runs-on: ubuntu-latest
    steps:
      - name: Debug context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JIRA_KEYS_JSON: ${{ needs.extract.outputs['jira-keys-json'] }}
        run: |
          echo "event_name='${{ github.event_name }}'"
          echo "action='${{ github.event.action }}'"
          echo "jira-keys-json='${JIRA_KEYS_JSON}'"
          echo "~~~~~~~~~~~ GitHub Context ~~~~~~~~~~~"
          echo "$GITHUB_CONTEXT"

  details:
    needs: extract
    uses: scylladb/github-automation/.github/workflows/extract_jira_issue_details.yml@main
    with:
      jira_keys_json: ${{ needs.extract.outputs['jira-keys-json'] }}
    secrets:
      jira_auth: ${{ secrets.caller_jira_auth }}

  apply_labels_to_pr:
    needs: [extract, details]
    uses: scylladb/github-automation/.github/workflows/apply_labels_to_pr.yml@main
    with:
      pr_number:  ${{ github.event.pull_request.number }}
      labels_csv: ${{ needs.details.outputs.labels_csv }}
      details_csv: ${{ needs.details.outputs.csv }}
      
  add_comment_to_jira:
    name: Add 'PR closed' comment to Jira issues
    needs: extract
    # Run only when PR was closed by a successful merge, and when we actually have Jira keys
    if: >
      github.event.pull_request.merged == true &&
      needs.extract.outputs['jira-keys-json'] != '["__NO_KEYS_FOUND__"]'
    strategy:
      matrix:
        jira_key: ${{ fromJson(needs.extract.outputs['jira-keys-json']) }}
    uses: scylladb/github-automation/.github/workflows/add_comment_to_jira.yml@main
    with:
      jira_key: ${{ matrix.jira_key }}
      comment: >
        Closed via PR "${{ github.event.pull_request.title }}"
        https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}
    secrets:
      jira_auth: ${{ secrets.caller_jira_auth }}

  jira_status_transition:
    name: Transition Jira issues to Done
    needs: [extract, details]
    # Run only when PR was closed by a successful merge (and we have some Jira keys in details)
    if: github.event.pull_request.merged == true
    uses: scylladb/github-automation/.github/workflows/jira_transition.yml@main
    with:
      details_csv:     ${{ needs.details.outputs.csv }}   # full CSV text
      transition_name: "Done"
      transition_id:   "141"
    secrets:
      jira_auth: ${{ secrets.caller_jira_auth }}
