name: Update Status - Ready For Merge

on:
  workflow_call:
    secrets:
      caller_jira_auth:
        required: true

jobs:
  extract:
    uses: scylladb/github-automation/.github/workflows/extract_jira_keys.yml@automation-staging-branch
    with:
      pr_title: ${{ github.event.pull_request.title }}
      pr_body:  ${{ github.event.pull_request.body }}

  transition:
    needs: extract
    if: ${{ github.event.label.name == 'status/merge_candidate' }}
    uses: scylladb/github-automation/.github/workflows/jira_transition.yml@automation-staging-branch
    with:
      jira_key: ${{ matrix.jira_key }}
      transition_name: "Ready For Merge"
      transition_id: "131"
    secrets:
      jira_auth: ${{ secrets.caller_jira_auth }}
    strategy:
      matrix:
        jira_key: ${{ fromJSON(needs.extract.outputs.jira-keys-json || '[]') }}
