name: Update Jira Status - In Review

on:
  workflow_call:
    secrets:
      caller_jira_auth:
        required: true

jobs:
  extract:
    uses: scylladb/github-automation/.github/workflows/extract_jira_keys.yml@main
    with:
      pr_title: ${{ github.event.pull_request.title }}
      pr_body:  ${{ github.event.pull_request.body }}

  transition:
    needs: extract
    if: ${{ needs.extract.outputs.jira-keys-json != '[]' }}
    uses: scylladb/github-automation/.github/workflows/jira_transition.yml@main
    with:
      jira_key: ${{ matrix.jira_key }}
      transition_name: "In Review"
      transition_id: "121"
    secrets:
      jira_auth: ${{ secrets.caller_jira_auth }}
    strategy:
      matrix:
        jira_key: ${{ fromJSON(needs.extract.outputs.jira-keys-json) }}
