name: Update Jira Status - In Review

on:
  workflow_call:
    secrets:
      caller_jira_auth:
        required: true

jobs:
  extract:
    uses: scylladb/github-automation/.github/workflows/extract_jira_keys.yml@automation-staging-branch
    with:
      pr_title: ${{ github.event.pull_request.title }}
      pr_body:  ${{ github.event.pull_request.body }}
    secrets:
      jira_auth: ${{ secrets.caller_jira_auth }}
      
  debug:                         
    needs: extract               
    runs-on: ubuntu-latest
    steps:       
      - name: Debug data
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |         
          echo "event_name='${{ github.event_name }}'"
          echo "action='${{ github.event.action }}'"
          echo "jira-keys-json='${{ needs.extract.outputs['jira-keys-json'] }}'"
          echo "~~~~~~~~~~~ GitHub Context ~~~~~~~~~~~"
          echo "$GITHUB_CONTEXT"
          
  details:
    needs: extract
    uses: scylladb/github-automation/.github/workflows/extract_jira_issue_details.yml@automation-staging-branch
    with:
      jira_keys_json: ${{ needs.extract.outputs['jira-keys-json'] }}
    secrets:
      jira_auth: ${{ secrets.caller_jira_auth }}

  apply_labels:
    needs: [extract, details]
    uses: scylladb/github-automation/.github/workflows/apply_labels_to_pr.yml@automation-staging-branch
    with:
      pr_number:  ${{ github.event.pull_request.number }}
      labels_csv: ${{ needs.details.outputs.labels_csv }}

  transition:
    needs: [extract, details]
    uses: scylladb/github-automation/.github/workflows/jira_transition.yml@automation-staging-branch
    with:
      details_csv:     ${{ needs.details.outputs.csv }}     # full CSV text
      transition_name: "In Review"
      transition_id: "121"
    secrets:
      jira_auth: ${{ secrets.caller_jira_auth }}

