name: Update Status - Ready For Merge

on:
  workflow_call:
    secrets:
      caller_jira_auth:
        required: true

jobs:
  extract:
    uses: scylladb/github-automation/.github/workflows/extract_jira_keys.yml@automation-staging-branch
    with:
      pr_title: ${{ github.event.pull_request.title }}
      pr_body:  ${{ github.event.pull_request.body }}

  debug:                         
    needs: extract               
    runs-on: ubuntu-latest
    steps:       
      - name: Debug data
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |         
          echo "event_name='${{ github.event_name }}'"
          echo "action='${{ github.event.action }}'"
          echo "jira-keys-json='${{ needs.extract.outputs['jira-keys-json'] }}'"
          echo "triggering-label='${{ github.event.label.name }}'"
          label="${{ github.event.label.name }}"
                    
          if [ -n "$label" ] && [ "$label" = "status/merge_candidate" ]; then
            echo "Try to transition Jira issue to 'Ready For Merge'"
          fi
          
          echo "~~~~~~~~~~~ GitHub Context ~~~~~~~~~~~"
          echo "$GITHUB_CONTEXT"


  # Retrieve details per jira key
  details:
    needs: extract
    uses: scylladb/github-automation/.github/workflows/extract_jira_issue_details.yml@automation-staging-branch
    secrets:
      jira_auth: ${{ secrets.caller_jira_auth }}
    strategy:
      matrix:
        jira_key: ${{ fromJSON(
          (needs.extract.outputs['jira-keys-json'] != '' &&
           needs.extract.outputs['jira-keys-json'] != '[]' &&
           needs.extract.outputs['jira-keys-json'] != '[""]')
            && needs.extract.outputs['jira-keys-json']
            || '["__NO_KEYS_FOUND__"]') }}
        exclude:
          - jira_key: "__NO_KEYS_FOUND__"
    with:
      jira_key: ${{ matrix.jira_key }}

  transition:
    needs: [extract, details]
    if: ${{ github.event.label.name == 'status/merge_candidate' }}
    uses: scylladb/github-automation/.github/workflows/jira_transition.yml@automation-staging-branch
    with:
      jira_key: ${{ matrix.jira_key }}
      transition_name: "Ready For Merge"
      transition_id: "131"
      current_jira_status:   ${{ needs.details.outputs.current_jira_status }}
    secrets:
      jira_auth: ${{ secrets.caller_jira_auth }}
    strategy:
      matrix:
        jira_key: ${{ fromJSON(
          (needs.extract.outputs['jira-keys-json'] != '' &&
           needs.extract.outputs['jira-keys-json'] != '[]' &&
           needs.extract.outputs['jira-keys-json'] != '[""]')
            && needs.extract.outputs['jira-keys-json']
            || '["__NO_KEYS_FOUND__"]') }}
        exclude:
          - jira_key: "__NO_KEYS_FOUND__"
