name: Update Jira Status - In Review

on:
  workflow_call:
    secrets:
      caller_jira_auth:
        required: true

jobs:
  extract:
    uses: scylladb/github-automation/.github/workflows/extract_jira_keys.yml@automation-staging-branch
    with:
      pr_title: ${{ github.event.pull_request.title }}
      pr_body:  ${{ github.event.pull_request.body }}

  debug:                         
    needs: extract               
    runs-on: ubuntu-latest
    steps:       
      - name: Debug data
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |         
          echo "event_name='${{ github.event_name }}'"
          echo "action='${{ github.event.action }}'"
          echo "jira-keys-json='${{ needs.extract.outputs['jira-keys-json'] }}'"
          echo "~~~~~~~~~~~ GitHub Context ~~~~~~~~~~~"
          echo "$GITHUB_CONTEXT"
          
  # Retrieve details per jira key
  details:
    needs: extract
    uses: scylladb/github-automation/.github/workflows/extract_jira_issue_details.yml@automation-staging-branch
    secrets:
      jira_auth: ${{ secrets.caller_jira_auth }}
    strategy:
      matrix:
        jira_key: ${{ fromJSON(
          (needs.extract.outputs['jira-keys-json'] != '' &&
           needs.extract.outputs['jira-keys-json'] != '[]' &&
           needs.extract.outputs['jira-keys-json'] != '[""]')
            && needs.extract.outputs['jira-keys-json']
            || '["__NO_KEYS_FOUND__"]') }}
        exclude:
          - jira_key: "__NO_KEYS_FOUND__"
    with:
      jira_key: ${{ matrix.jira_key }}

apply_labels:
    needs: [extract, details]
    uses: scylladb/github-automation/.github/workflows/apply_labels_to_pr.yml@automation-staging-branch
    with:
      pr_number:  ${{ github.event.pull_request.number }}
      labels_csv: ${{ needs.details.outputs.current_jira_labels }}
    strategy:
      matrix:
        jira_key: ${{ fromJSON(
          (needs.extract.outputs['jira-keys-json'] != '' &&
           needs.extract.outputs['jira-keys-json'] != '[]' &&
           needs.extract.outputs['jira-keys-json'] != '[""]')
            && needs.extract.outputs['jira-keys-json']
            || '["__NO_KEYS_FOUND__"]') }}
        exclude:
          - jira_key: "__NO_KEYS_FOUND__"

  transition:
    needs: [extract, details]
    uses: scylladb/github-automation/.github/workflows/jira_transition.yml@automation-staging-branch
    with:
      jira_key: ${{ matrix.jira_key }}
      transition_name: "In Review"
      transition_id: "121"
      current_jira_status:   ${{ needs.details.outputs.current_jira_status }}
    secrets:
      jira_auth: ${{ secrets.caller_jira_auth }}
    strategy:
      matrix:
        jira_key: ${{ fromJSON(
          (needs.extract.outputs['jira-keys-json'] != '' &&
           needs.extract.outputs['jira-keys-json'] != '[]' &&
           needs.extract.outputs['jira-keys-json'] != '[""]')
            && needs.extract.outputs['jira-keys-json']
            || '["__NO_KEYS_FOUND__"]') }}
        exclude:
          - jira_key: "__NO_KEYS_FOUND__"
